# syntax=docker/dockerfile:1

# Build input program
FROM golang:1.24
WORKDIR /src
COPY ./papeador-submission.go ./main.go
RUN go build -o /bin/submission ./main.go



# Create sandbox
FROM busybox:latest

# Write file
COPY ./papeador.sh /bin/papeador
COPY ./alive.sh /bin/alive

COPY ./timelimit.txt /tmp/timelimit.txt
COPY ./inputs /tmp/inputs
COPY ./expected-outputs /tmp/expected-outputs

RUN chmod -R 600 /tmp/timelimit.txt
RUN chmod -R 600 /tmp/inputs
RUN chmod -R 600 /tmp/expected-outputs

RUN adduser runner -D

RUN chmod 755 /bin/papeador
RUN chmod 755 /bin/alive

COPY --from=0 /bin/submission /bin/submission
CMD ["papeador"]